databases:
  - name: church_mgt
    databaseName: church_mgt_production
    user: church_mgt_user
    plan: free

services:
  - type: web
    name: church_mgt
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: church_mgt
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: "2"
