databases:
  - name: postgresql
    databaseName: church_mgt_production  # Match the production database name in database.yml
    user: postgres
    plan: free

services:
  - type: web
    name: church_mgt
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -b 0.0.0.0"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: "2" # sensible default
