default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: wolo
  pool: 5

development:
  <<: *default
  database: church_mgt_development

test:
  <<: *default
  database: church_mgt_test

production:
  <<: *default
  database: church_mgt_production
  url: <%= ENV['DATABASE_URL'] %>
